name: CI

on:
  pull_request:
    branches:
      - main
      - infra/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install yarn
        run: npm install -g yarn

      - name: Install 
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test